### ISSUE TITLE
Packages cannot accept hopper input from every face.

### ISSUE THREAD

**Issue by KirinDave** [quat1024/packages#10]
While Packages suggest they aim to have a similar interface to shulker boxes, they are not compatible with many shulker box builds because they have a "display" face that cannot accept hopper input. For example, the [popular 1-wide tilable shulker box loader](https://youtu.be/3ceYUDzSX7o?t=221) that is often deployed cannot use packages because the dispenser places them from below, facing upwards towards the hopper.

While it is possible to modify loader and unloader builds to use packages, it seems like packages already have significant limitations that prevent them from overwhleming the shulker box use cases. And given their rather small default inventory and need for nested loader designs to get the most out of them, incompatibilities with proven loader designs makes them much harder to use.

**Comment by quat1024** [comment]
Oh! Didn't think about that.
