### ISSUE TITLE
[1.18.2 Forge] packages won't accept modded methods of interacting with items

### ISSUE THREAD

**Issue by Flyte-less** [quat1024/packages#16]
It seems that most mods can't insert/extract/read the contents of a package with the exception of botania's corpora which can extract from packages but can't insert for some reason (pictured).

![image](https://user-images.githubusercontent.com/83427235/197943382-7ef4c643-6dcd-4df4-be72-225e9860118f.png)

**Comment by quat1024** [comment]
Mods need to support vanilla `Container`, forge used to wrap containers with iitemhandler im pretty sure but i guess they dont anymore because this loader is ass

**Comment by quat1024** [comment]
Thinks about it for 3 more nanoseconds after sleeping a bit

I guess it's not that hard to use the forge capabilities system to implement `IItemHandler`.. workin on it

**Comment by quat1024** [comment]
Yeah, that wasn't so hard

![image](https://user-images.githubusercontent.com/2068021/198179816-3930fb4a-7747-4891-a958-be1054b3a173.png)

**Comment by quat1024** [comment]
check for version 3.1, there's no Fabric release with this version because there were no fabric changes (so the version numbers are now out-of-step)
