### ISSUE TITLE
Compatibility - Packages v1.0 for MC 1.16.1 and Sodium v0.1.0

### ISSUE THREAD

**Issue by rxay579** [quat1024/packages#2]
When I add Sodium to my installed mods, it breaks Packages pretty thoroughly.
If I relaunch without Sodium, the packages work normally.

Tested in superflat world with just Fabric API, Packages, and Sodium.

Log With Sodium
[latest.log](https://github.com/quat1024/packages/files/4973424/latest.log)

Log Without Sodium
[latest.log](https://github.com/quat1024/packages/files/4973437/latest.log)

Packages With Sodium
![2020-07-24_12 19 54](https://user-images.githubusercontent.com/67221030/88417899-5f94ab80-cda8-11ea-93f0-8fc0a03bf477.png)
![2020-07-24_12 20 01](https://user-images.githubusercontent.com/67221030/88417903-61f70580-cda8-11ea-8e46-925554f3f095.png)

**Comment by quat1024** [comment]
oh, thanks for reporting this to gh, was meaning to look into it.

I think this is because Sodium doesn't implement the fabric rendering apis, which i make heavy use of to implement the retexturable blocks. I don't know if there's anything i can do but i can maybe look into a more sensible fallback model.

**Comment by rxay579** [comment]
Reporting on Sodium's Github as well.  Sodium looks like it's still working stuff out so I'm not expecting any kind of quick fix.
Love having this storage problem BTW.

**Comment by quat1024** [comment]
Just gonna drop a link to Sodium's tracking issue here: https://github.com/jellysquid3/sodium-fabric/issues/5 , although I feel a bit bad about adding to the wall of linked issue reports 😅 

I'm not sure what the best stopgap is; maybe I could use a block entity renderer (like chests) if Sodium is present. It won't look as good but it's at least better than pink square

**Comment by quat1024** [comment]
Closing this issue because it's very old, i hope you can understand lol. Newer versions of Sodium for newer versions implement enough of FRAPI to cause less-egregiously-bad rendering, and you can install Indium to fix the rest, so I'm not very interested in adding more fallback renderers.

**Comment by rxay579** [comment]
Yeah, no problem.
Seem like it's not really your issue (Fabric project using Fabric renderer) and looks like you have a more recent version of the same issue up anyway.
https://github.com/quat1024/packages/issues/7
