### ISSUE TITLE
(Feature Request) Use of ink sacs to change how items display on packages.

### ISSUE THREAD

**Issue by Bobisnotap** [quat1024/packages#20]
This is partly inspired by the create contraption issue from earlier, normal ink sacks could be used on packages to make items render as a pure black silhouette, and in addition glow ink sacks could be used to render the items like on glow item frames.
I'm not entirely sure on what would be the best implementation of this, as just using the sacks on the sides of packages would be odd, and using the sacks in the dye slot of package creation would make this feature not compatible with dyes.

**Comment by quat1024** [comment]
Half the selling point of Packages is that when they have the same contents, they stack; adding permanent upgrades messes that up because you'd have to upgrade every block in the stack and it just becomes a mess.
