### ISSUE TITLE
[Fabric 1.19.2] Game freezes when trying to create a package

### ISSUE THREAD

**Issue by kingkuys2123** [quat1024/packages#22]
In the latest update, I tried creating a package with stones and planks and the moment I tried putting in the stone as the frame of the package the game freezes..

**Comment by quat1024** [comment]
Well that sucks! pretty sure i tested this shit. Gimme a minute

**Comment by quat1024** [comment]
Oh, shit, the code for drawing the empty-slot tooltip is completely broken. That's embarassing.

**Comment by quat1024** [comment]
This is fixed in the version 3.4. I'm really sorry for all the hotfixing i've been doing
