### ISSUE TITLE
[Forge 1.18] Dispensers don't place packages in world

### ISSUE THREAD

**Issue by Pecant-Pie** [quat1024/packages#29]
Using mod version 1.18.2-3.4, with forge, the dispensers do not place down the packages. Activating a dispenser with a package in it just shoots the item out :(. I see that this was a bug with the 1.19.2 version as well and was fixed, so hopefully this isn't a big deal.

**Comment by Pecant-Pie** [comment]
I'm testing it on a cloned repo and it seems like the method actuallyRegisterDispenserBehaviors() within the ForgePlatformSupport class is never run, so the behavior is never actually added to the dispenser.

**Comment by Pecant-Pie** [comment]
I just confirmed that dispensers place packages as expected on fabric 1.18.2 for the same mod version.

**Comment by quat1024** [comment]
sorry about that !

**Comment by quat1024** [comment]
ok, This is in mod version "3.4.0.1" for 1.18 forge only. (it's not numbered 3.4.1 because that was for 1.19 and included more significant changes that i did not back port.) Thank you for reporting
