### ISSUE TITLE
Texture issues in 1.16.3

### ISSUE THREAD

**Issue by Derpford** [quat1024/packages#4]
So, *TECHNICALLY* this isn't out for 1.16.3, but it does run; and when it does...packages render weird.
It's not consistent, but they seem to use utterly random textures, including flower textures of all things.

**Comment by quat1024** [comment]
Ah dammit I must have broken something with the update that made it work better with Canvas; basically redid the whole model system. Thanks for the report, i'd like to try and make it work on as many 1.16 versions as i can.

Can you post some screenshots and send a mod list? sometimes other mods can interfere.

**Comment by quat1024** [comment]
Going to close this issue because it's very old and I don't have the time to support 1.16 anymore, I hope you can understand.
